### PR TITLE
Fix/enable decoupled tan submission

### LINKED ISSUE #131: Sparkasse import stopped working
Unfortunally my connection to Sparkasse stopped working. I would appreciate to get some help. The error is:

```

Warning: Undefined array key 921 in /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php on line 60

Fatal error: Uncaught Error: Call to a member function needsTanMedium() on null in /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php:32 Stack trace: #0 /var/www/html/firefly-iii-fints-importer/app/Choose2FADevice.php(25): App\FinTsFactory::create_from_session() #1 /var/www/html/firefly-iii-fints-importer/app/index.php(55): App\StepFunction\Choose2FADevice() #2 {main} thrown in /var/www/html/firefly-iii-fints-importer/app/FinTsFactory.php on line 32
```
...I guess Sparkasse changed something (again), but they won't help anymore. Maybe here someone can help? I'm more than happy to get into debugging stuff.

My configuration:
```
{
  "bank_username": "A",
  "bank_password": "",
  "bank_code": "56050180",
  "bank_url": "https://banking-rp3.s-fints-pt-rp.de/fints30",
  "bank_2fa": "921",
  "firefly_url": "http://127.0.0.1",
  "firefly_access_token": "key",
  "skip_transaction_review": "false",
  "__description_regex_comment__": "To disable the regex search & replace of the transaction description, set both to an empty string.",
  "description_regex_match": "",
  "description_regex_replace": ""
}
```

what's safed in `$tanModes` might be interesting as well:  
```
    [923] => Fhp\Segment\TAN\VerfahrensparameterZweiSchrittVerfahrenV7 Object
        (
            [sicherheitsfunktion] => 923
            [tanProzess] => 2
            [technischeIdentifikationTanVerfahren] => pushTAN-cas
            [dkTanVerfahren] => Decoupled
            [versionDkTanVerfahren] => 
            [nameDesZweiSchrittVerfahrens] => pushTAN 2.0
            [maximaleLaengeDesTanEingabewertes] => 
            [erlaubtesFormat] => 
            [textZurBelegungDesRueckgabewertes] => Aufforderung
            [maximaleLaengeDesRueckgabewertes] => 2048
            [mehrfachTanErlaubt] => 1
            [tanZeitUndDialogbezug] => 2
            [auftragsstornoErlaubt] => 
            [smsAbbuchungskontoErforderlich] => 0
            [auftraggeberkontoErforderlich] => 0
            [challengeKlasseErforderlich] => 
            [challengeStrukturiert] => 
            [initialisierungsmodus] => 00
            [bezeichnungDesTanMediumsErforderlich] => 2
            [antwortHhdUcErforderlich] => 
            [anzahlUnterstuetzterAktiverTanMedien] => 5
            [maximaleAnzahlStatusabfragen] => 180
            [wartezeitVorErsterStatusabfrage] => 1
            [wartezeitVorNaechsterStatusabfrage] => 1
            [manuelleBestaetigungMoeglich] => 1
            [automatisierteStatusabfragenErlaubt] => 1
        )
```

Thanks a lot for your help!

### PR DESCRIPTION
**Pull request by JuliusFreudenberger**
This is my second attempt to fix #131 after #142 was merged but had a problem related to outdated dependencies.
It includes the same commits and an additional commit updating the nemiah/phpfints dependency.
I used the following command `composer update nemiah/php-fints phpspec/prophecy phpunit/phpunit`. prophecy and phpunit had to be updated as well (I guess it is related to the requirement of php>=8.0).
Using a locally built docker container I could also import statements successfully, so I think the current dependency situation should not lead to any more problems.

This also brings up the question if anything else has to be done due to the new requirement php>=8.0?

To keep everything together, here also the important part of the description of the old PR:
This adds the basic functionality for decoupled TAN checks, presented by phpFinTs.
I could confirm this working with my Sparkasse bank account.

However, this implementation has a caveat: Confirming the import in the pushTAN app is necessary every time an import is started. Also this adds an entry to the list of saved devices in device management (Geräteverwaltung).
This is also an issue in phpFinTs: https://github.com/nemiah/phpFinTS/issues/453, where it is described as an issue with the "kundensystemId"

### CODE REVIEW

**Comment by bnw** [comment]
Again, thanks a lot! 😊
The current dockerfile already uses php 8.1, so this should not be a problem.
It’s normal that updating one package also requires updating some others. But these ones are probably not problematic 👍

**Comment by JuliusFreudenberger** [comment]
I did another test in the docker environment using the image provided by you and I did not encounter any errors.
Now I can import my statements into firefly again.

**Comment by UebertreibeR** [comment]
Hi @JuliusFreudenberger , 
were you able to work around the issue of having to manually confirm pushTAN on every import?  There has to be a solution as it works fine for 90 days on other (paid) platforms once a device is added as "trustworthy"

**Comment by JuliusFreudenberger** [comment]
As you opened #149, I will answer there.

**Pull request merged**
