### PR TITLE
partial bank login

### PR DESCRIPTION
**Pull request by TyrionWarMage**
Just a small change that enables to define the bank username by config (or request), but not the password (and vice versa).

### CODE REVIEW

**Comment by bnw** [comment]
Hi,
thanks a lot for your contribution. 
Unfortunately, I dislike this implicit mechanism of setting password or username. I think with the proposed state, you will be the only user of this feature, because, without looking at the code, nobody would know it exists.
At the very least, I think this mechanism should be explained in the form: "If you leave this field empty, this and that will happen".
The best option imo would be to prefill the form with the values that are already set in the config.

**Comment by TyrionWarMage** [comment]
Hi, i think there is a misunderstanding. This PR is more a fix than a feature:

Before, when only setting the username, but not the password via config, both username and password had not been prefilled. This was due to https://github.com/bnw/firefly-iii-fints-importer/blob/54d0b9b1548dfde02e5edf9aaa1b944edf7f87d8/app/CollectData.php#L27, where one missing results in both beeing replaced by the (empty) request parameter.

Now, username and password are checked indepdently, meaning when setting the username but not the password via config, the form will be prefilled with the username but still be shown for the password.

Therefore, i think it works as you requested?

**Comment by bnw** [comment]
Hi,
sorry for the delay and my confusion. You are completely right, the form is prefilled with the username, if the username is present in the config and the password is not.  
If it is the other way around and only the password is set in the config file, the password is not prefilled in the form. I think this is reasonable behavior, because we want to prevent somebody on the network to simply read out the password from the config file.

However, one thing is still off, imo:
If the user prefills only the username and not the password in the config file, he is presented with the partially filled form. If in this form the user now changes the username, this modified username will not be picked up. Instead, the username from the config will override the username set in the form. Could you make sure that the username submitted via the form will be picked up correctly in this case? :)

**Comment by TyrionWarMage** [comment]
> However, one thing is still off, imo: If the user prefills only the username and not the password in the config file, he is presented with the partially filled form. If in this form the user now changes the username, this modified username will not be picked up. Instead, the username from the config will override the username set in the form. Could you make sure that the username submitted via the form will be picked up correctly in this case? :)

Good catch, fixed

**Comment by bnw** [comment]
Thanks a lot for your work :)

**Pull request merged**
